default: false

# Need to figure out how to make exceptions for pages/agent/v3/help/_*
#MD002:
  # Heading level
  #level: 1

MD003:
  # Heading style
  style: "consistent"

# MD004/ul-style - Unordered list style
MD004:
  # List style
  style: "sublist"

# MD005/list-indent - Inconsistent indentation for list items at the same level
MD005: true

# MD006/ul-start-left - Consider starting bulleted lists at the beginning of the line
MD006: true

# MD007/ul-indent - Unordered list indentation
# (This setting is temporarily disabled. The intention is to make its value 4, as doing this would allow the nesting of 3 bullet points and improved code block handling)
# MD007:
  # Spaces for indent
  # indent: 2
  # Whether to indent the first level of the list
  # start_indented: false

# MD009/no-trailing-spaces - Trailing spaces
MD009:
  # Spaces for line break
  br_spaces: 2
  # Allow spaces for empty lines in list items
  list_item_empty_lines: false
  # Include unnecessary breaks
  strict: false

MD023: true # Headings at start of line

MD025:
  # Heading level
  level: 1

MD042: true

# MD047/single-trailing-newline - Files should end with a single newline character
MD047: true
