steps:
  - name: ":docker::ecr: Push to ECR"
    command: ".buildkite/push-image.sh"
    depends_on: "rspec"
    key: "ecr-push"
    if: |
      build.branch == "main"
    agents:
      queue: deploy
    plugins:
      ecr#v2.7.0:
        login: true
        account-ids: ${ECR_ACCOUNT_ID}

  - name: ":ecr: ECR Vulnerabilities Scan"
    command: "true"
    agents:
      queue: deploy
    depends_on: "ecr-push"
    plugins:
      - buildkite/ecr-scan-results#v1.2.0:
          image-name: "${ECR_REPO}:${BUILDKITE_BUILD_NUMBER}"
          ignore:
            - CVE-2023-29007 # git 1:2.39.2-1.1
            - CVE-2023-25652 # git 1:2.39.2-1.1
            - CVE-2021-3864 # linux 6.1.55-1
            - CVE-2013-7445 # linux 6.1.55-1
            - CVE-2019-19814 # linux 6.1.55-1
            - CVE-2019-19449 # linux 6.1.55-1
            - CVE-2021-3847 # linux 6.1.55-1
            - CVE-2023-35827 # linux 6.1.55-1
            - CVE-2023-2953 # openldap 2.5.13+dfsg-5
            - CVE-2023-31484 # perl 5.36.0-7
            - CVE-2023-24329 # python3.11 3.11.2-6
            - CVE-2023-3640 # linux 6.1.55-1
            - CVE-2023-45853 # zlib 1:1.2.13.dfsg-1
            - CVE-2023-5717 # linux 6.1.55-1

  # If the current user is part of the deploy team, then wait for everything to
  # finish before deploying
  - wait: ~
    key: "deploy-check-wait"
    depends_on: "ecr-push"
    if: "(build.creator.teams includes 'deploy') && build.branch == 'main'"

  # If the user *isn't* in the deploy team, require a block step for manual
  # verification by someone who is in the team.
  - block: ":rocket: Deploy"
    key: "deploy-check-block"
    depends_on: "ecr-push"
    if: "!(build.creator.teams includes 'deploy') && build.branch == 'main'"

  - label: ":docker::rocket:"
    branches: main
    depends_on:
      - "deploy-check-wait"
      - "deploy-check-block"
    concurrency: 1
    concurrency_group: docs-deploy
    agents:
      queue: deploy
    command: scripts/deploy-ecs

  - wait

  # Refresh the search index after a deployment
  - label: "🔎🪄"
    trigger: docs-algolia-crawler
    async: true
