env:
  GITHUB_USERNAME: "buildkite-docs-bot"

steps:
  - label: "Prepare preview"
    command: bin/prepare-preview

  - label: "Deploy preview"
    command: bin/deploy-preview
    plugins:
      - ailohq/github-deployment#v1.0.10:
          token-env: GH_TOKEN
          environment: preview
          production_environment: false
          transient_environment: true
      - docker-compose#v3.9.0:
          run: app
          config: docker-compose.production.yml
          mount-buildkite-agent: true
          env:
            - GH_TOKEN
            - NETLIFY_AUTH_TOKEN
            - NETLIFY_SITE_ID
            - BUILDKITE_BRANCH
